#!/bin/sh

execute() {
	$@ > /dev/null 2>&1
	STATUS=$?

	if [ $? -ne 0 ]; then
		echo "Failed running: $@"
		return ${STATUS}
	fi
}


execute iwpriv wlan0 mp_stop
execute ifconfig wlan0 down
execute modprobe -r 8723ds
